title: Page
icon: file-text-o 
pages: true
files:
  fields:
    license: license
    copyright: copyright
options:
  # delete: false
  template: false
  url: false
  status: false
fields:
  title: title
  description: description
  text: text
  postimage: postimage
  submenu:
    label: Show submenu
    type: hidden
    text: Do you want to display the submenu?
  line:
    type: line
  seotitle: seotitle
