title: Page
pages: true
files:
  fields:
    copyright:
      label: Copyright
      type: text
    caption:
      label: Caption
      type: text
fields:
  title:
    label: Title
    type:  text
  description:
    label: Description
    type:  text
  text:
    label: Text
    type:  textarea
  postimage:
    label: Main Post Image
    type:  selector
    mode:  single
    types:
        - image
  submenu:
    label: Show submenu
    type: checkbox
    text: Do you want to display the submenu?
