title: Page
pages: true
files:
  fields:
    copyright:
      label: Copyright
      type: text
    caption:
      label: Caption
      type: text
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
