title: Page
icon: file-text-o 
pages: true
files:
  fields:
    copyright: copyright
    caption: caption
options:
  delete: false
  template: false
  url: false
  status: false
fields:
  title: title
  description: description
  text: text
  postimage:
    label: Main Post Image
    type:  selector
    mode:  single
    types:
        - image
  submenu:
    label: Show submenu
    type: hidden
    text: Do you want to display the submenu?
  line:
    type: line
  seotitle: seotitle
