title: Project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
  description: description
  year:
    label: Year
    type:  text
  text:
    label: Text
    type:  textarea
  tags:
    label: Tags
    type:  tags
  submenu:
    label: Show submenu
    type: checkbox
    text: Do you want to display the submenu?
  line:
    type: line
  seotitle: seotitle
