title: Site
pages: true
fields:
  title:
    label: Title
    type:  text
  author:
    label: Author
    type:  text
  description: description
  keywords:
    label: Keywords
    type:  tags
  facebook:
    label: Facebook link
    type:  text
  instagram:
    label: Instagram link
    type:  text
  twitter:
    label: Twitter link
    type:  text
  copyright:
    label: Copyright
    type:  textarea
  submenu:
    label: Show submenu
    type: checkbox
    text: Do you want to display the submenu?
  line:
    type: line
  seotitle: seotitle
